/**
 * React Native mapping for color.css. Keep values and semantic keys aligned
 * with the CSS custom properties so every platform speaks the same tokens.
 */
export const referenceColor = {
  white: '#FFFFFF',
  black: '#000000',
  ink900: '#121C2A',
  ink700: '#454654',
  ink500: '#757686',
  indigo700: '#424A84',
  indigo600: '#4F5795',
  indigo500: '#6870AF',
  indigo200: '#DFE9FC',
  indigo150: '#E6EEFF',
  indigo100: '#EFF3FF',
  indigo50: '#F8F9FF',
  sky100: '#E6F4FE',
  blue600: '#2563EB',
  blue50: '#EAF2FF',
  cyan700: '#006879',
  green500: '#2ECC71',
  red500: '#FF6B6B',
  red700: '#BA1A1A',
  red50: '#FFEDEA',
  neutral300: '#C5C5D6',
  neutral150: '#E6E8F1',
  indigoOnBrand: '#DDE1FF',
  shadowBrand: '#515A97'
} as const

export const colorCssVariable = {
  brand: '--lifee-color-brand',
  brandPressed: '--lifee-color-brand-pressed',
  brandGradientEnd: '--lifee-color-brand-gradient-end',
  brandSoft: '--lifee-color-brand-soft',
  brandSurface: '--lifee-color-brand-surface',
  accent: '--lifee-color-accent',
  background: '--lifee-color-background',
  appIconBackground: '--lifee-color-app-icon-background',
  surface: '--lifee-color-surface',
  surfaceTranslucent: '--lifee-color-surface-translucent',
  surfaceSubtle: '--lifee-color-surface-subtle',
  surfaceCalendar: '--lifee-color-surface-calendar',
  surfaceModal: '--lifee-color-surface-modal',
  surfaceHeader: '--lifee-color-surface-header',
  surfaceControl: '--lifee-color-surface-control',
  categorySurface: '--lifee-color-category-surface',
  text: '--lifee-color-text',
  textSecondary: '--lifee-color-text-secondary',
  textTertiary: '--lifee-color-text-tertiary',
  textDisabled: '--lifee-color-text-disabled',
  onBrand: '--lifee-color-on-brand',
  onBrandMuted: '--lifee-color-on-brand-muted',
  border: '--lifee-color-border',
  borderOverlay: '--lifee-color-border-overlay',
  borderPanel: '--lifee-color-border-panel',
  divider: '--lifee-color-divider',
  income: '--lifee-color-income',
  expense: '--lifee-color-expense',
  danger: '--lifee-color-danger',
  dangerSurface: '--lifee-color-danger-surface',
  actionEdit: '--lifee-color-action-edit',
  actionEditSurface: '--lifee-color-action-edit-surface',
  actionDelete: '--lifee-color-action-delete',
  actionDeleteSurface: '--lifee-color-action-delete-surface',
  disabled: '--lifee-color-disabled',
  backdrop: '--lifee-color-backdrop',
  cursor: '--lifee-color-cursor',
  shadow: '--lifee-color-shadow',
  shadowBrand: '--lifee-color-shadow-brand'
} as const

export const lightColor = {
  brand: referenceColor.indigo600,
  brandPressed: referenceColor.indigo700,
  brandGradientEnd: referenceColor.indigo500,
  brandSoft: referenceColor.indigo150,
  brandSurface: referenceColor.indigo100,
  accent: referenceColor.cyan700,
  background: referenceColor.indigo50,
  appIconBackground: referenceColor.sky100,
  surface: referenceColor.white,
  surfaceTranslucent: 'rgba(255,255,255,0.80)',
  surfaceSubtle: 'rgba(255,255,255,0.56)',
  surfaceCalendar: 'rgba(255,255,255,0.48)',
  surfaceModal: 'rgba(248,249,255,0.97)',
  surfaceHeader: 'rgba(248,249,255,0.92)',
  surfaceControl: 'rgba(223,233,252,0.50)',
  categorySurface: referenceColor.indigo200,
  text: referenceColor.ink900,
  textSecondary: referenceColor.ink700,
  textTertiary: referenceColor.ink500,
  textDisabled: 'rgba(117,118,134,0.50)',
  onBrand: referenceColor.white,
  onBrandMuted: referenceColor.indigoOnBrand,
  border: referenceColor.neutral300,
  borderOverlay: 'rgba(255,255,255,0.70)',
  borderPanel: 'rgba(255,255,255,0.50)',
  divider: 'rgba(197,197,214,0.30)',
  income: referenceColor.green500,
  expense: referenceColor.red500,
  danger: referenceColor.red700,
  dangerSurface: referenceColor.red50,
  actionEdit: referenceColor.blue600,
  actionEditSurface: referenceColor.blue50,
  actionDelete: referenceColor.red700,
  actionDeleteSurface: referenceColor.red50,
  disabled: referenceColor.neutral150,
  backdrop: 'rgba(18,28,42,0.18)',
  cursor: 'rgba(79,87,149,0.30)',
  shadow: referenceColor.black,
  shadowBrand: referenceColor.shadowBrand
} as const satisfies Record<keyof typeof colorCssVariable, string>

export type ColorTokenName = keyof typeof colorCssVariable
export type ColorTokens = Record<ColorTokenName, string>
